# this is ....
[app]
title = "my app"

[server]
runMode = "debug"
host = "localhost"
port = 9001

[database]
dBType = "mysql"
userName = "root"
password = "zhangying"
host = "127.0.0.1:3306"
dBName = "quick"
tablePrefix = "zy_"
charset = "utf8mb4"
parseTime = true
maxIdleConns = 10
maxOpenConns = 30

[Email]
Enabled = true
Host = "smtp.qq.com"
Port = 465
UserName = "my App Admin"
Password = "1234567890"
IsSSL = true
From = "admin@xxxx1234yyyy.com"
poolSize = 0

[Log]
filename = "./app.log"
maxSize = 10
mxBackups = 5
maxAge = 1
compress = false
